//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneyComb.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCR_CONTENT_ENCRYPTION
    {
        public string ENCRYPTION_ID { get; set; }
        public string CONTENT_INFO_ID { get; set; }
        public string ENCRYPTED_NAME { get; set; }
    }
}
