//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneyComb.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCR_SUBJECT_GROUP
    {
        public MCR_SUBJECT_GROUP()
        {
            this.MCR_SUBJECT = new HashSet<MCR_SUBJECT>();
        }
    
        public string SUBJECT_GROUP_ID { get; set; }
        public string SCHOOL_LEVEL_ID { get; set; }
        public string SUBJECT_GROUP_NAME { get; set; }
        public string SUBJECT_GROUP_DESCRIPT { get; set; }
    
        public virtual ICollection<MCR_SUBJECT> MCR_SUBJECT { get; set; }
    }
}
