//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneyComb.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCR_QUESTIONS
    {
        public MCR_QUESTIONS()
        {
            this.MCR_ANSWERS = new HashSet<MCR_ANSWERS>();
        }
    
        public string QUESTIONS_ID { get; set; }
        public string ASSESSMENT_ID { get; set; }
        public string QUESTION_TYPE_ID { get; set; }
        public string LEVEL_ID { get; set; }
        public string QUESTION_DESCRIPTION { get; set; }
        public string PAGE_NUMBER { get; set; }
        public string CHAPTER_NUMBER { get; set; }
        public string CHAPTER_NAME { get; set; }
        public string ACTIVE { get; set; }
    
        public virtual ICollection<MCR_ANSWERS> MCR_ANSWERS { get; set; }
        public virtual MCR_ASSESSMENT MCR_ASSESSMENT { get; set; }
        public virtual MCR_QUESTION_TYPE MCR_QUESTION_TYPE { get; set; }
        public virtual MCR_WEIGHT_LEVEL MCR_WEIGHT_LEVEL { get; set; }
    }
}
