//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneyComb.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCR_SUBJECT
    {
        public MCR_SUBJECT()
        {
            this.MCR_CONTENT_ALLOCATE = new HashSet<MCR_CONTENT_ALLOCATE>();
        }
    
        public string SUBJECT_ID { get; set; }
        public string SUBJECT_GROUP_ID { get; set; }
        public string GRADE_ID { get; set; }
        public string LANGUAGE_LEVEL_ID { get; set; }
        public string SUBJECT_NAME { get; set; }
        public string SUBJECT_DESCRIPTION { get; set; }
    
        public virtual ICollection<MCR_CONTENT_ALLOCATE> MCR_CONTENT_ALLOCATE { get; set; }
        public virtual MCR_GRADE MCR_GRADE { get; set; }
        public virtual MCR_LANGUAGE_LEVEL MCR_LANGUAGE_LEVEL { get; set; }
        public virtual MCR_SUBJECT_GROUP MCR_SUBJECT_GROUP { get; set; }
    }
}
