//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneyComb.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCR_CONTENT_ALLOCATE
    {
        public string ALLOCATE_ID { get; set; }
        public string CONTENT_ID { get; set; }
        public string SCHOOL_ID { get; set; }
        public string GRADE_ID { get; set; }
        public string SUBJECT_ID { get; set; }
        public string SCHOOL_SUBJECT_ID { get; set; }
        public string ALLOCATED { get; set; }
    
        public virtual MCR_SCHOOL MCR_SCHOOL { get; set; }
        public virtual MCR_SUBJECT MCR_SUBJECT { get; set; }
    }
}
