//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneyComb.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCR_CITY
    {
        public string CITY_ID { get; set; }
        public string DISTRICT_ID { get; set; }
        public string CITY_NAME { get; set; }
    
        public virtual MCR_DISTRICT MCR_DISTRICT { get; set; }
    }
}
