//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneyComb.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCR_DISTRICT
    {
        public MCR_DISTRICT()
        {
            this.MCR_CITY = new HashSet<MCR_CITY>();
        }
    
        public string DISTRICT_ID { get; set; }
        public string PROVINCE_ID { get; set; }
        public string DISTRICT_NAME { get; set; }
    
        public virtual ICollection<MCR_CITY> MCR_CITY { get; set; }
        public virtual MCR_PROVINCE MCR_PROVINCE { get; set; }
    }
}
