//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneyComb.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCR_ASSESSMENT
    {
        public MCR_ASSESSMENT()
        {
            this.MCR_QUESTIONS = new HashSet<MCR_QUESTIONS>();
        }
    
        public string ASSESSMENT_ID { get; set; }
        public string CONTENT_INFO_ID { get; set; }
        public string ASSESSMENT_NAME { get; set; }
        public string PAGE_NUMBER { get; set; }
        public string CHAPTER_NUMBER { get; set; }
        public string CHAPTER_NAME { get; set; }
        public string ACTIVE { get; set; }
    
        public virtual ICollection<MCR_QUESTIONS> MCR_QUESTIONS { get; set; }
        public virtual MCR_CONTENT_INFO MCR_CONTENT_INFO { get; set; }
    }
}
