//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneyComb.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCR_CONTENT_LOCATION
    {
        public string LOCATION_ID { get; set; }
        public string CONTENT_INFO_ID { get; set; }
        public string CONTENT_TITLE { get; set; }
        public string CONTENT_URL { get; set; }
        public string SMALL_THUMBNAIL_NAME { get; set; }
        public string SMALL_THUMBNAIL_URL { get; set; }
        public string MEDIUM_THUMBNAIL_NAME { get; set; }
        public string MEDIUM_THUMBNAIL_URL { get; set; }
        public string LARGE_THUMBNAIL_NAME { get; set; }
        public string LARGE_THUMBNAIL_URL { get; set; }
    
        public virtual MCR_CONTENT_INFO MCR_CONTENT_INFO { get; set; }
    }
}
