//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneyComb.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCR_LOGIN
    {
        public decimal USER_CODE { get; set; }
        public string LOGIN_USERNAME { get; set; }
        public string LOGIN_PASSWORD { get; set; }
        public string USER_TYPE { get; set; }
        public Nullable<decimal> LOGIN_ATTEMPTS { get; set; }
        public string USER_STATUS { get; set; }
        public Nullable<System.DateTime> LOGIN_TIMESTAMP { get; set; }
        public string LOGIN_IMAGE_URL { get; set; }
    }
}
