//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneyComb.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCR_QUESTION_TYPE
    {
        public MCR_QUESTION_TYPE()
        {
            this.MCR_QUESTIONS = new HashSet<MCR_QUESTIONS>();
        }
    
        public string QUESTION_TYPE_ID { get; set; }
        public string QUESTION_TYPE_NAME { get; set; }
        public string ABRREVIATION { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<MCR_QUESTIONS> MCR_QUESTIONS { get; set; }
    }
}
