//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneyComb.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCR_WEIGHT_LEVEL
    {
        public MCR_WEIGHT_LEVEL()
        {
            this.MCR_ASSESSMENT_WEIGHT = new HashSet<MCR_ASSESSMENT_WEIGHT>();
            this.MCR_QUESTIONS = new HashSet<MCR_QUESTIONS>();
        }
    
        public string LEVEL_ID { get; set; }
        public string LEVEL_NAME { get; set; }
        public string LEVEL_DESCRIPTION { get; set; }
    
        public virtual ICollection<MCR_ASSESSMENT_WEIGHT> MCR_ASSESSMENT_WEIGHT { get; set; }
        public virtual ICollection<MCR_QUESTIONS> MCR_QUESTIONS { get; set; }
    }
}
