//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneyComb.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCR_COUNTRY
    {
        public MCR_COUNTRY()
        {
            this.MCR_PROVINCE = new HashSet<MCR_PROVINCE>();
        }
    
        public string COUNTRY_ID { get; set; }
        public string COUNTRY_NAME { get; set; }
    
        public virtual ICollection<MCR_PROVINCE> MCR_PROVINCE { get; set; }
    }
}
