//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneyComb.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCR_PERSONS
    {
        public decimal USER_CODE { get; set; }
        public string LOGIN_USERNAME { get; set; }
        public string LOGIN_PASSWORD { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string GENDER { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public System.DateTime DATE_OF_BIRTH { get; set; }
        public string IDENTITY_NUMBER { get; set; }
        public string NATIONALITY { get; set; }
        public string ROLE_CODE { get; set; }
        public string USER_STATUS { get; set; }
    }
}
