//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneyComb.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCR_SCHOOL
    {
        public MCR_SCHOOL()
        {
            this.MCR_CONTENT_ALLOCATE = new HashSet<MCR_CONTENT_ALLOCATE>();
        }
    
        public string SCHOOL_ID { get; set; }
        public string COUNTRY_ID { get; set; }
        public string PROVINCE_ID { get; set; }
        public string DISTRICT_ID { get; set; }
        public string CITY_ID { get; set; }
        public string EXAM_BOARD_ID { get; set; }
        public string SCHOOL_TYPE_ID { get; set; }
        public string SCHOOL_LEVEL_ID { get; set; }
        public string SCHOOL_NAME { get; set; }
        public string SCHOOL_LANGUAGE { get; set; }
        public string CONTACT_PERSON { get; set; }
        public string CONTACT_NUMBER { get; set; }
    
        public virtual ICollection<MCR_CONTENT_ALLOCATE> MCR_CONTENT_ALLOCATE { get; set; }
        public virtual MCR_EXAM_BOARD MCR_EXAM_BOARD { get; set; }
        public virtual MCR_SCHOOL_LEVEL MCR_SCHOOL_LEVEL { get; set; }
        public virtual MCR_SCHOOL_TYPE MCR_SCHOOL_TYPE { get; set; }
    }
}
