//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneyComb.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCR_CONTENT_INFO
    {
        public MCR_CONTENT_INFO()
        {
            this.MCR_ASSESSMENT = new HashSet<MCR_ASSESSMENT>();
            this.MCR_CONTENT_LOCATION = new HashSet<MCR_CONTENT_LOCATION>();
        }
    
        public string CONTENT_INFO_ID { get; set; }
        public string CONTENT_ID { get; set; }
        public string SUBJECT_ID { get; set; }
        public string TEXT_ISBN { get; set; }
        public string TEXT_TITLE { get; set; }
        public string TEXT_AUTHOR { get; set; }
        public string NO_OF_CHAPTERS { get; set; }
        public string NO_OF_PAGES { get; set; }
        public string TEXT_DESCRIPTION { get; set; }
    
        public virtual ICollection<MCR_ASSESSMENT> MCR_ASSESSMENT { get; set; }
        public virtual ICollection<MCR_CONTENT_LOCATION> MCR_CONTENT_LOCATION { get; set; }
    }
}
